id: AFB4EFBCA
title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
type: translation
pechas:
- I2B249684
- IB49B24A3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:29:22.507320
  last_modified_at: 2023-01-04 11:29:22.507329
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I2B249684/3984: 384C
  IB49B24A3/E2E8: 384C
